version: '3.9'

services:

  unifi-network-application:
    image: iot/unifi-network-application:7.2.92
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - UNIFI_VERSION_MAJOR=7
        - UNIFI_VERSION_MINOR=2
        - UNIFI_VERSION_PATCH=92
        - PUID=1000
        - PGID=1000
    platform: linux/arm64
    container_name: ${COMPOSE_PROJECT_NAME}-unifi_network_application
    depends_on:
      - unifi-network-application-mongo
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    networks:
      - piot_network
    ports:
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8080:8080/tcp" # Device/controller communication
      - "10001:10001/udp" # AP discovery
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
    restart: unless-stopped
    volumes:
      - ./data/unifi:/config
      #- unifi_mongo_data:/config/data/db

  unifi-network-application-mongo:
    image: mongo:3.6.23
    platform: linux/arm64
    container_name: ${COMPOSE_PROJECT_NAME}-unifi_network_application-mongo
    networks:
      - piot_network
    restart: unless-stopped
    volumes:
      -   unifi_mongo_data:/data/db

  homebridge:
    image: oznu/homebridge:latest
    platform: linux/arm64
    container_name: ${COMPOSE_PROJECT_NAME}-homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./data/homebridge:/homebridge

volumes:
  unifi_mongo_data:

networks:
  piot_network:
