version: "3.9"

services:

  unifi-network-application:
    image: iot/unifi-network-application:7.3.76
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - UNIFI_VERSION_MAJOR=7
        - UNIFI_VERSION_MINOR=3
        - UNIFI_VERSION_PATCH=76
        - PUID=1000
        - PGID=1000
    platform: linux/arm64
    container_name: ${COMPOSE_PROJECT_NAME}-unifi_network_application
    profiles:
      - primary
    depends_on:
      - unifi-network-application-mongo
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    networks:
      - piot_network
    ports:
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8080:8080/tcp" # Device/controller communication
      - "10001:10001/udp" # AP discovery
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
    restart: unless-stopped
    volumes:
      - ./data/unifi:/config
      #- unifi_mongo_data:/config/data/db

  unifi-network-application-mongo:
    image: mongo:3.6.23
    platform: linux/arm64
    container_name: ${COMPOSE_PROJECT_NAME}-unifi_network_application-mongo
    profiles:
      - primary
    networks:
      - piot_network
    restart: unless-stopped
    volumes:
      - unifi_mongo_data:/data/db

  homebridge:
    image: oznu/homebridge:2023-01-08-ubuntu
    platform: linux/arm64
    container_name: ${COMPOSE_PROJECT_NAME}-homebridge
    profiles:
      - primary
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    network_mode: host
    volumes:
      - ./data/homebridge:/homebridge

  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    image: pihole/pihole:latest
    container_name: ${COMPOSE_PROJECT_NAME}-pihole
    profiles:
      - secondary
    environment:
      - TZ=America/New_York
      - FTLCONF_REPLY_ADDR4=192.168.1.212
      - ADMIN_EMAIL=iot@rudolph.team
      - WEBPASSWORD_FILE=data/pihole/webpassword.txt
    # For DHCP, it is recommended to remove these ports and instead add: network_mode: "host"
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    #  - "80:80/tcp"
    network_mode: host
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)
    restart: unless-stopped
    # Volumes store your data between container upgrades
    volumes:
      - ./data/pihole/etc-pihole:/etc/pihole
      - ./data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

volumes:
  unifi_mongo_data:

networks:
  piot_network:
